const imageStage=document.getElementById('imageStage');const moduleStage=document.getElementById('moduleStage');const title=document.getElementById('moduleTitle');const body=document.getElementById('moduleBody');const backBtn=document.getElementById('backBtn');const homeBtn=document.getElementById('homeBtn');
let historyStack=['home'];let tempStep=1;const cache=new Map();
const names={scorecard:'Store Scorecard',alerts:'Open Alerts','associate-temp':'Associate Temperature Module',temperature:'Temperature',sales:'Sales',labor:'Labor',production:'Production',inventory:'Inventory',ordering:'Ordering','fresh-start':'Fresh Start',safety:'Safety',shrink:'Shrink','food-safety':'Food Safety',console:'F.R.I.E.N.D. Console',voice:'Voice Interface',maximo:'Maximo'};
function preload(){['images/home.png',...Array.from({length:6},(_,i)=>`images/temper${i+1}.png`)].forEach(src=>{const img=new Image();img.src=src;cache.set(src,img)})}
function go(target,push=true){if(target==='home'){showHome();return} if(push)historyStack.push(target); if(target==='associate-temp'){tempStep=1;showTemp()}else showModule(target)}
function showHome(){historyStack=['home'];moduleStage.hidden=true;imageStage.hidden=false;requestAnimationFrame(()=>{imageStage.classList.add('active');moduleStage.classList.remove('active')})}
function showModule(key){imageStage.classList.remove('active');setTimeout(()=>{imageStage.hidden=true;moduleStage.hidden=false;moduleStage.classList.add('active')},80);title.textContent=names[key]||'Module';body.innerHTML=moduleTemplate(key)}
function showTemp(){title.textContent='Associate Temperature Module';imageStage.classList.remove('active');setTimeout(()=>{imageStage.hidden=true;moduleStage.hidden=false;moduleStage.classList.add('active')},80);const src=`images/temper${tempStep}.png`;body.innerHTML=`<div class="moduleCard"><img class="screenPhoto" src="${src}" alt="Associate Temperature Module screen ${tempStep}" onerror="this.replaceWith(fallbackTemp(${tempStep}))"><button class="nextBtn" onclick="nextTemp()">${tempStep<6?'Next Temperature Screen':'Finish / Home'}</button><p class="muted">Screen ${tempStep} of 6 · swipe left/right or tap Next.</p></div>`}
function fallbackTemp(n){const div=document.createElement('div');div.className='moduleCard';div.innerHTML=`<h2>Temperature Module ${n}</h2><p>Add your real image as <b>images/temper${n}.png</b>. This route is already wired and works offline after the file is added.</p>`;return div}
function nextTemp(){if(tempStep<6){tempStep++;showTemp()}else showHome()}
function moduleTemplate(key){if(key==='voice')return `<div class="moduleCard"><h2>Voice Interface</h2><p>Microphone route is active. Use keywords like production, shrink, temperature, alerts, labor, sales, inventory, ordering, safety, food safety, fresh start, or maximo.</p><button class="nextBtn voiceOn" onclick="startVoice()">Start Voice</button></div>`;return `<div class="moduleCard"><h2>${names[key]||'Module'} is connected.</h2><p>This button is active and ready for its final screen image or live module content.</p></div><div class="metricGrid"><div class="metric"><span>Status</span><strong>Open</strong></div><div class="metric"><span>Navigation</span><strong>Ready</strong></div></div>`}
document.getElementById('hotspots').addEventListener('click',e=>{const b=e.target.closest('button[data-target]');if(!b)return;go(b.dataset.target)});
backBtn.onclick=()=>{historyStack.pop();const prev=historyStack.pop()||'home';go(prev,prev!=='home')};homeBtn.onclick=showHome;
let x0=null;document.addEventListener('touchstart',e=>{x0=e.touches[0].clientX},{passive:true});document.addEventListener('touchend',e=>{if(x0==null)return;const dx=e.changedTouches[0].clientX-x0;x0=null;if(Math.abs(dx)<55)return;if(title.textContent==='Associate Temperature Module'){if(dx<0&&tempStep<6){tempStep++;showTemp()}else if(dx>0&&tempStep>1){tempStep--;showTemp()}else if(dx>0)showHome()}},{passive:true});
function startVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert('Voice search is not available in this browser. Buttons still work.');return}const rec=new SR();rec.lang='en-US';rec.onresult=e=>{const t=e.results[0][0].transcript.toLowerCase();const found=Object.keys(names).find(k=>t.includes(k.replace('-',' '))||t.includes(names[k].toLowerCase()));if(found)go(found);else alert('Say a module name, like temperature or shrink.')};rec.start()}
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>{}));preload();
